import { type CommandResponse } from "../commandResponse";

export function handleHelpCommand(): CommandResponse {
  return {
    status: "ok",
    message: [
      "Meal Logging Bot help",
      "",
      "Available commands:",
      "",
      "/help",
      "Show this help message.",
      "",
      "/addInventory item_name=\"red lentils\" quantity=500 unit=g location=cupboard",
      "Add an item to inventory.",
      "",
      "/logMeal date=2026-04-23 meal_type=lunch items_text=\"rice, broccoli, seitan\" quantity_text=\"1 bowl\" energy_kcal=550",
      "Log a meal.",
      "",
      "/addProduct product_name=\"Greek yoghurt\" brand=\"Fage\" category=dairy",
      "Preview a product, then use /confirm or /cancel.",
      "",
      "/closeDay date=2026-04-23 mood=calm energy=medium appetite=normal notes=\"steady day\"",
      "Preview a daily note, then use /confirm or /cancel.",
      "",
      "/inventory",
      "List active inventory items.",
      "",
      "/useSoon",
      "List active items with the earliest use-by or best-before dates.",
      "",
      "/gptToday date=2026-04-23",
      "Return a compact today-focused handoff for Meal Planner GPT.",
      "",
      "/gptPlanContext",
      "Return a broader planning context handoff for Meal Planner GPT.",
      "",
      "/confirm",
      "Confirm the current pending preview action.",
      "",
      "/cancel",
      "Cancel the current pending preview action.",
    ].join("\n"),
  };
}
